services:
  - type: web
    name: discovery-service
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: backend/discovery-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker

  - type: web
    name: api-gateway
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: backend/api-gateway/Dockerfile
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service.onrender.com/eureka
      - key: SPRING_PROFILES_ACTIVE
        value: docker

  - type: web
    name: auth-service
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: backend/auth-service/Dockerfile
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service.onrender.com/eureka

  - type: web
    name: user-service
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: backend/user-service/Dockerfile
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service.onrender.com/eureka

  - type: web
    name: product-service
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: backend/product-service/Dockerfile
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service.onrender.com/eureka

  - type: web
    name: order-service
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: backend/order-service/Dockerfile
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service.onrender.com/eureka
